apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsxontap-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: fsxontap-nas