kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-filebrowser-vol
  namespace: default
  annotations:
    trident.netapp.io/unixPermissions: "0775"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: handson-anf-premium