apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: handson-anf-standard
  namespace: default
  annotations:
    trident.netapp.io/unixPermissions: "0775"  
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: handson-anf-standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: handson-anf-premium
  namespace: default
  annotations:
    trident.netapp.io/unixPermissions: "0775"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: handson-anf-premium