---
- name: Create a lab environment 
  hosts: localhost
  gather_facts: false
  vars:
    login: &login
      hostname: "xxx.xxx.xxx.xxx"
      username: "admin"
      password: "xxxxxxxxx"
      https: true
      validate_certs: false     
  vars_files:
    - vars/main.yml
  
  
  tasks:
  - name: Create My NetApp Storage SVM
    na_ontap_svm:
      state: present
      name: "svm-{{ userid }}"
      root_volume: "svm_{{ userid }}_root"
      root_volume_aggregate: aggr1
      root_volume_security_style: unix
      aggr_list: aggr1
      <<: *login
      
  - name: Create Storage Network Interface for NFS
    na_ontap_interface:
      state: present
      interface_name: "svm-{{ userid }}_dataLif"
      home_port: e0b
      home_node: OTC_Netapp_korea_lab-01
      role: data
      protocols: nfs
      admin_status: up
      is_auto_revert: true
      address: "{{ ipaddress_nfs }}"
      netmask: 255.255.255.0
      vserver: "svm-{{ userid }}"
      <<: *login

  - name: Create route
    na_ontap_net_routes:
      state: present
      vserver: "svm-{{ userid }}"
      destination: 10.2.0.0/16
      gateway: 10.255.100.100
      metric: 50
      <<: *login
      
  - name: Start NFS service
    na_ontap_nfs:
      state: present
      service_state: started
      vserver: "svm-{{ userid }}"
      nfsv3: enabled
      nfsv4: disabled
      nfsv41: disabled
      tcp: enabled
      udp: enabled
      vstorage_state: disabled
      <<: *login
      
  - name: Setup exports Policy
    na_ontap_export_policy_rule:
      state: present
      policy_name: default
      vserver: "svm-{{ userid }}"
      client_match: 0.0.0.0/0
      ro_rule: any
      rw_rule: any
      protocol: any
      super_user_security: any
      <<: *login
            
  - name: Create NFS volume
    na_ontap_volume:
      state: present
      name: "content"
      vserver: "svm-{{ userid }}"
      aggregate_name: aggr1
      size: 5 
      size_unit: gb
      policy: default
      junction_path: "/content"
      space_guarantee: none
      unix_permissions: "777"
      snapdir_access: "no"
      volume_security_style: unix
      <<: *login

  - name: Change Volume attributes
    na_ontap_command:
      command: ['volume','modify','-vserver','svm-{{ userid }}','-volume','content','-user','1000','-group','1000']
      <<: *login
