apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content
  namespace: ghost
  labels:
    app: ghost
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: netapp-csi
  resources:
    requests:
      storage: 5Gi
