apiVersion: v1
kind: Service
metadata:
  name: nginx-file-bro-svc
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: nginx-file-bro